In [41]:
#importing numpy in your project
import numpy as np

#dimensions
    #x
    #x,y
    #x,y,z
#shapes(telling about number of rows,cols,width in image depending upon array)
    #cols
    #rows by cols
    #rows by cols by width
#size(telling about total number of elements in array)
    


In [2]:
#checking the version of numpy
np.version.version

'1.19.2'

In [9]:
#-----------------------------------------------1D array(collection of numbers)
myArray = np.array([1,2,3,4,5])
print(type(myArray))
print(myArray.ndim)                          #for 1D=x,2D=x,y,3D=x,y,z
print(myArray.shape)
print(myArray.size)
print(myArray.dtype)

<class 'numpy.ndarray'>
1
(5,)
5
int32


In [14]:
#------------------------------------------------2D array(collection of 1D arrays)
myArray2=np.array([
                    [1,2,3],     #1d
                    [4,5,6],     #1d
                    [7,8,9]      #1d
                ])
print(myArray2.ndim,myArray2.shape,myArray2.size)

2 (3, 3) 9


In [39]:
#------------------------------------------------3D array(collection of 2D array)
myArray3=np.array([
    #2d
        [
            [1,2,3,4],
            [4,5,6,5],
            [7,8,9,6]
        ], 
    #2d
        [
            [1,2,3,5],
            [4,5,6,6],
            [7,8,9,7]
        ], 
    #2d
        [
             [1,2,3,1],
             [4,5,6,2],
             [7,8,9,3]
        ], 
    #2d
        [
            [1,2,3,4],
            [4,5,6,5],
            [7,8,9,6]
        ],
    #2d
        [
             [1,2,3,1],
             [4,5,6,2],
             [7,8,9,3]
        ]
])

print(myArray3.ndim)
print(myArray3.shape)
print(myArray3.size)

3
(5, 3, 4)
60


In [33]:
#creating array of zeroes
zarr=np.zeros((2,2,2))
print(zarr)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [24]:
#creating array of ones
oarr=np.ones((3,5))
print(oarr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
#creating array of 18
oarr=np.ones((5,5))*18
print(oarr)

[[18. 18. 18. 18. 18.]
 [18. 18. 18. 18. 18.]
 [18. 18. 18. 18. 18.]
 [18. 18. 18. 18. 18.]
 [18. 18. 18. 18. 18.]]


In [30]:
#create constant array
carr=np.full((5,7),456)
carr[0][0]=126
print(carr)

[[126 456 456 456 456 456 456]
 [456 456 456 456 456 456 456]
 [456 456 456 456 456 456 456]
 [456 456 456 456 456 456 456]
 [456 456 456 456 456 456 456]]


In [28]:
#create an identity matrix
iarr=np.eye(10)
print(iarr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [29]:
rarr=np.random.random((3,3))
print(rarr)

[[0.22360854 0.03081277 0.41884753]
 [0.10443953 0.25536181 0.25116763]
 [0.7257112  0.69270706 0.92463646]]


In [40]:
myArray=np.array([['r','e','d'],
             [5,6,7]])
print(type(myArray))
print(myArray.ndim)                          #for 1D=x,2D=x,y,3D=x,y,z
print(myArray.shape)
print(myArray.size)
print(myArray.dtype)

<class 'numpy.ndarray'>
2
(2, 3)
6
<U1
